# This YAML file contains attacher & csi driver API objects,
# which are necessary to run external csi provisioner for cinder.

kind: Service
apiVersion: v1
metadata:
  name: csi-provisioner-nedgeplugin
  labels:
    app: csi-provisioner-nedgeplugin
spec:
  selector:
    app: csi-provisioner-nedgeplugin
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: csi-provisioner-nedgeplugin
spec:
  serviceName: "csi-provisioner-nedgeplugin"
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-provisioner-nedgeplugin
    spec:
      serviceAccount: csi-provisioner
      containers:
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v0.2.0
          args:
            - "--provisioner=csi-nedgeplugin"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: nfs
          image: 10.3.30.75:5000/nexentaedge-csi-plugin:latest
          args :
            - "--nodeid=$(NODE_ID)"
            - "--endpoint=$(CSI_ENDPOINT)"
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix://plugin/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /plugin
            - name: secret
              mountPath: /config
              readOnly: true
      volumes:
        - name: socket-dir
          emptyDir:
        - name: secret
          secret:
            secretName: nexentaedge-cluster